apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon off
        Log_Level info
        Parsers_File parsers.conf

    # akash-provider
    [INPUT]
        Name tail
        Tag kube.var.log.containers.akash-provider-0_${HOSTNAME}
        Path /var/log/containers/akash-provider-0_*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.akash-provider*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.akash-provider*
        Add cluster_name $CLUSTER_NAME
        Add container_name akash-provider-0

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.akash-provider*
        Host 100.70.2.34
        Port 32100
        Labels cluster_name=$CLUSTER_NAME,container_name=akash-provider-0
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # operator-hostname
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-hostname_${HOSTNAME}
        Path /var/log/containers/operator-hostname-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-hostname*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-hostname*
        Add cluster_name $CLUSTER_NAME
        Add container_name operator-hostname

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-hostname*
        Host 100.70.2.34
        Port 32100
        Labels cluster_name=$CLUSTER_NAME,container_name=operator-hostname
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # operator-inventory
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-inventory_${HOSTNAME}
        Path /var/log/containers/operator-inventory-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-inventory*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-inventory*
        Add cluster_name $CLUSTER_NAME
        Add container_name operator-inventory

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory*
        Host 100.70.2.34
        Port 32100
        Labels cluster_name=$CLUSTER_NAME,container_name=operator-inventory
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # operator-inventory-hardware-discovery
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-inventory-hardware-discovery_${HOSTNAME}
        Path /var/log/containers/operator-inventory-hardware-discovery-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-inventory-hardware*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-inventory-hardware*
        Add cluster_name $CLUSTER_NAME
        Add container_name operator-inventory-hardware-discovery

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory-hardware*
        Host 100.70.2.34
        Port 32100
        Labels cluster_name=$CLUSTER_NAME,container_name=operator-inventory-hardware-discovery
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # operator-ip
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-ip_${HOSTNAME}
        Path /var/log/containers/operator-ip-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-ip*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-ip*
        Add cluster_name $CLUSTER_NAME
        Add container_name operator-ip

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-ip*
        Host 100.70.2.34
        Port 32100
        Labels cluster_name=$CLUSTER_NAME,container_name=operator-ip
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Kubernetes Events Input
    [INPUT]
        Name              kubernetes_events
        Tag               kube.events
        Interval_Sec      1
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Token_TTL   600

    # Filter for Kubernetes Events
    [FILTER]
        Name          modify
        Match         kube.events
        Add          cluster_name h100-mon-obl-akash-pub
        Add          log_type    k8s_events

    # Output for Kubernetes Events
    [OUTPUT]
        Name          loki
        Match         kube.events
        Host          100.70.2.34
        Port          32100
        Labels        cluster_name=h100-mon-obl-akash-pub,log_type=k8s_events
        Label_Keys    $cluster_name,$log_type
        Line_Format   json
        Auto_Kubernetes_Labels false

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
