clusterName: ""        # ðŸ‘ˆ REQUIRED â€“ e.g. "prod-eu-west"
loki:
  # Primary Loki endpoint
  host: ""             # ðŸ‘ˆ REQUIRED â€“ IP or DNS name, e.g. "100.70.2.34"
  port: 32100          # change if your Loki is on another port
  
  # Secondary Loki endpoint
  secondary:
    host: ""           # ðŸ‘ˆ OPTIONAL â€“ IP or DNS name for second endpoint
    port: 32100        # change if your secondary Loki is on another port
  
  # Tertiary Loki endpoint
  tertiary:
    host: ""           # ðŸ‘ˆ OPTIONAL â€“ IP or DNS name for third endpoint
    port: 32100        # change if your tertiary Loki is on another port

image:
  repository: fluent/fluent-bit
  tag: 2.1.10
  pullPolicy: IfNotPresent
namespace: "monitoring"

